// src/lib/datasheets.mjs: one place for product datasheet file names.
// The PDFs are generated by tools/datasheets.mjs into assets/datasheets/.

export const datasheetFile = (slug) => `securetrust-${String(slug).replace(/^products\//, '')}-datasheet.pdf`;
export const datasheetPath = (slug) => `datasheets/${datasheetFile(slug)}`;